### ISSUE TITLE
Dependency on Old Alamofire. Causes compile Errors

### ISSUE THREAD

**Issue by jasonboggess** [cloudconvert/cloudconvert-swift#1]
Trying to compile with version CloudConvert 1.0.1, but it depends on Alamofire `1.2`. This version of Alamo fire uses the old version of swift which no longer works in XCode 7.1.1. This causes many swift compile errors (57+ in total). (such as '#' has been removed from Swift).

The newest version of Alamofire is 3.1.3 (https://github.com/Alamofire/Alamofire/blob/master/Alamofire.podspec). Updating should fix these compile issues.

**Comment by josiasmontag** [comment]
This wrapper is based on Swift 1.2 and not yet compatible/tested with Swift 2.0. We will fix this in the following weeks. If you can easily fix this on your own, PRs are also welcome.

**Comment by jasonboggess** [comment]
I checked out the repo and tried to update to Alamofire 3. Most of the compile errors were gone, but there were still a few things needing changed. The Alamofire API changed slightly (mostly around error handling), but there were some swift-specific errors that I wasn't sure how to fix. 

I'm a swift noob, so not sure if I'm the best person for this task.

**Comment by josiasmontag** [comment]
Should work now with the current version of XCode/Swift. Let me know if there are still any issues.

**Comment by jasonboggess** [comment]
Thanks for the amazingly fast turn around!
