### ISSUE TITLE
Support for Alamofire 4.0 / Swift 3.0 / Xcode 8.0

### ISSUE THREAD

**Issue by structAnkit** [cloudconvert/cloudconvert-swift#4]
It seems there is a lot of work to be done to make this compatible with the above dependency versions. I've gotten pretty far but the main blocker is the response serialization as the Alamofire project went a different direction with it.

Is there any progress made in this regard so far?

**Comment by josiasmontag** [comment]
For sure we will update the wrapper at some point. Unfortunately I cannot give you any schedule because we currently do not have direct need for this. 
If you need Swift 3 compatibility now please update the wrapper on your own. PRs are very welcome.

**Comment by jasonboggess** [comment]
This is now a blocking issue as XCode 8.3 does not support swift before 3 anymore.

**Comment by Enriquecm** [comment]
I created a fork compatibility for Swift 3+/Xcode 8+:
https://github.com/Enriquecm/cloudconvert-swift

I tested only the pdf conversion. Feel free to try the other features.
As soon as possible I will make a PR for this repository.

**Comment by jasonboggess** [comment]
I'm having trouble getting that branch to compile. Getting Swift Compiler Errors in the AlamoFire 3.5.1 package.

**Comment by jasonboggess** [comment]
I think I got it to work with Alamofire 4.0:

https://github.com/jasonboggess/cloudconvert-swift

**Comment by Enriquecm** [comment]
Hi @jasonboggess , The trouble to compile is about the current CloudConvert version or my fork?

**Comment by jasonboggess** [comment]
Your fork. I updated my podfile to point to your repo and the workspace wouldn't compile.

**Comment by Enriquecm** [comment]
Hi @jasonboggess , I think you got the wrong branch or the wrong commit.

If you still need it, or some other developer needs this update.
Put the code below into your Podfile:

```
pod 'CloudConvert' , :git => 'https://github.com/Enriquecm/cloudconvert-swift.git', :commit => '5ca42909c585b274fd5caefe4be6d2c0a8e00ee0'
```

**Comment by josiasmontag** [comment]
See See https://github.com/cloudconvert/cloudconvert-swift/pull/7
